version: '3.4'

services:
  nginx:
    ports:
      - "443:443"
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    networks: 
      - docker_network
    depends_on: 
      - mariadb
    #volumes:
      #- wordpress_data:/var/www/html/wordpress

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    env_file:
      - .env
    networks: 
      - docker_network
    volumes:
      - mariadb_v:/var/lib/mysql

  #wordpress:
    #container_name: wordpress
    #build: ./requirements/wordpress
    #restart: unless-stopped
    #env_file:
     # - .env
    #depends_on: 
     # - mariadb
    #networks: 
     # - docker_network
    #volumes:
      #- wordpress_data:/var/www/html/wordpress
      
networks:
    docker_network:

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aperis/data/mariadb
  #wordpress_data:
   # driver: local
    #driver_opts:
     # type: none
      #device: /home/aperis/data/wordpress
     # o: bind