version: '3.4'

services:
  nginx:
    ports:
      - "443:443"
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    networks: 
      - docker_network
    depends_on: 
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress

  mariadb:
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    networks: 
      - docker_network
    volumes:
      - mariadb_v:/var/run/mysqld

  wordpress:
    environment:
      - WP_NAME=${WP_NAME}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_ROOT_PASSWORD=${WP_ROOT_PASSWORD}
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    depends_on: 
      - mariadb
    networks: 
      - docker_network
    volumes:
      - wordpress_data:/var/www/html/wordpress
      
networks:
    docker_network:

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aperis/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/aperis/data/wordpress
      o: bind