version: '3.4'

networks:
    docker_network:
    lee:

services:

  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    networks: 
      - docker_network
    volumes:
      - mariadb_v:/var/run/mysqld

  wordpress:
    env_file:
      - .env
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    depends_on: 
      - mariadb
    networks: 
      - docker_network
      - lee
    volumes:
      - wordpress_data:/var/www/html/wordpress

  nginx:
    ports:
      - "443:443"
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    networks: 
      - lee
    depends_on: 
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress
      
volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aperis/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/aperis/data/wordpress
      o: bind