version: '3.4'

services:
  nginx:
    ports:
      - "443:443"
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless_stoped
    env_file:
      - .env