service mysql start

echo "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
mysql -e "CREATE DATABASE 'aperis';"
mysql -e "CREATE USER 'aperis'@'%' IDENTIFIED BY 'perisa';"
mysql -e "GRANT ALL PRIVILEGES ON 'aperis'.* TO 'aperis'@'%' IDENTIFIED BY 'perisa';"
mysql -e "FLUSH PRIVILEGES;"
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root4life';"
echo "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
