CREATE DATABASE IF NOT EXISTS wordpress;

CREATE USER $DB_USER@'%';
SET PASSWORD FOR $DB_USER@'%' = PASSWORD($DB_USER_PASSWORD);
GRANT ALL PRIVILEGES ON wordpress.* TO $DB_USER@'%' IDENTIFIED BY $DB_USER_PASSWORD;
FLUSH PRIVILEGES;